apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deploy
  namespace: python
  labels:
    app: admin-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
      environment: dev
  template:
    metadata:
      labels:
        app: admin-service
        environment: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5003"
    spec:
      containers:
        - name: admin-service
          image: jeevanugale/admin_service:test-18b12f36cbbd1e80ee743b6c122c9737789c45fb
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: app-configs
            - secretRef:
                name: app-secrets
                
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"