services:
  admin-service:
    image: jeevanugale/admin_service:main-eda45735aeb526cb4f3f8182f7d176568d4120cb
    container_name: admin
    ports:
      - "5003:5003"
    env_file:
      - .env

  user-service:
    image: jeevanugale/user_service:main-eda45735aeb526cb4f3f8182f7d176568d4120cb
    container_name: user
    ports:
      - "5002:5002"
    env_file:
      - .env

  auth-service:
    image: jeevanugale/auth_service:main-eda45735aeb526cb4f3f8182f7d176568d4120cb
    container_name: auth
    ports:
      - "5001:5001"
    env_file:
      - .env

  web-frontend:
    image: jeevanugale/web_frontend:main-eda45735aeb526cb4f3f8182f7d176568d4120cb
    container_name: web
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - admin-service
      - user-service
      - auth-service