services:
  admin-service:
    image: jeevanugale/admin_service:test-99e41c94b8fc751aa938565e338f653fe9c18988
    container_name: admin
    ports:
      - "5003:5003"
    env_file:
      - .env

  user-service:
    image: jeevanugale/user_service:test-99e41c94b8fc751aa938565e338f653fe9c18988
    container_name: user
    ports:
      - "5002:5002"
    env_file:
      - .env

  auth-service:
    image: jeevanugale/auth_service:test-99e41c94b8fc751aa938565e338f653fe9c18988
    container_name: auth
    ports:
      - "5001:5001"
    env_file:
      - .env

  web-frontend:
    image: jeevanugale/web_frontend:test-99e41c94b8fc751aa938565e338f653fe9c18988
    container_name: web
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - admin-service
      - user-service
      - auth-service