apiVersion: v2
name: python-app
description: A Helm chart for the Python microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - python
  - microservices
  - flask
maintainers:
  - name: Jeevan Ugale
    email: jeevanugale@gmail.com
