apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.user.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.services.user.labels.app }}
    environment: {{ .Values.global.environment }}

spec:
  replicas: {{ .Values.services.user.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.user.labels.app }}
      environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.user.labels.app }}
        environment: {{ .Values.global.environment }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.services.user.port }}"

    spec:
      containers:
        - name: {{ .Values.services.user.labels.app }}
          image: {{ .Values.services.user.image.repository }}:{{ .Values.services.user.image.tag }}
          imagePullPolicy: {{ .Values.services.user.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.user.port }}
          envFrom:
            - configMapRef:
                name: app-configs
            - secretRef:
                name: app-secrets

          livenessProbe:
            httpGet:
              path: {{ .Values.services.user.livenessProbe.path }}
              port: {{ .Values.services.user.port }}
            initialDelaySeconds: {{ .Values.services.user.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.services.user.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.services.user.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.services.user.livenessProbe.failureThreshold }}

          resources:
            requests:
              memory: {{ .Values.services.user.resources.requests.memory }}
              cpu: {{ .Values.services.user.resources.requests.cpu }}
            limits:
              memory: {{ .Values.services.user.resources.limits.memory }}
              cpu: {{ .Values.services.user.resources.limits.cpu }}
