apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.user.labels.app }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.services.user.labels.app }}
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: {{ .Values.services.user.labels.app }}
    environment: {{ .Values.global.environment }}
  ports:
    - port: {{ .Values.services.user.port }}
      targetPort: {{ .Values.services.user.port }}
  type: ClusterIP
