apiVersion: v1
kind: Service
metadata:
  name: db-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    environment: {{ .Values.global.environment }}
spec:
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  clusterIP: None
---
apiVersion: k8s.io/v1
kind: Endpoints
metadata:
  name: db-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    environment: {{ .Values.global.environment }}
subsets:
  - addresses:
      - ip: {{ .Values.db.host }}
    ports:
      - port: {{ .Values.db.port }}
