apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
  namespace: python
  labels:
    app: python-app
    environment: dev
data:
  # DATABASE CONFIG
  DB_HOST: "db-server"
  DB_PORT: "3306"
  DB_NAME: "users_db"

  # SERVICE PORTS
  ADMIN_SERVICE_PORT: "5003"
  USER_SERVICE_PORT: "5002"
  AUTH_SERVICE_PORT: "5001"
  WEB_FRONTEND_PORT: "5000"

  # SERVICE URL's
  ADMIN_SERVICE_URL: "http://admin-service:5003"
  USER_SERVICE_URL: "http://user-service:5002"
  AUTH_SERVICE_URL: "http://auth-service:5001"

  # LOGIING AND ENVIRONMENT
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "dev"
  DEBUG: "False"

  # REQUEST SETTINGS
  REQUEST_TIMEOUT: "10"
  HOST: "0.0.0.0"