apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: python
  labels:
    app: python-app
    environment: dev
type: Opaque
data:
  DB_USER: "Zmxhc2t1c2Vy"
  DB_PASS: "Zmxhc2twYXNz"
  MYSQL_ROOT_PASSWORD: "cm9vdA=="

  SECRET_KEY: "MXFhejJ3c3gzZWRjNHJmdg=="
  JWT_SECRET:  "NXRnYjZ5aG43dWptOGlrLA=="

  ADMIN_USERNAME: "YWRtaW4="
  ADMIN_PASSWORD_HASH: "c3NjcnlwdDozMjc2ODo4OjFPMVM1Y0ZwYTlJSVZGN3NmOTA4YjUzMjczYTc3NGJhM2NiOTAwNTFiZDAxN2IzM2IwZWI5YTc2NzM5NzNiNWQwZTZiNGZiZTE2ZmM1MjMyYzMzMWVlODk1YWFlNTFlMmVlZDUxY2QyOWUzYWMzMTg1N2NjNTQ4MjNjNzc0N2E5NzAzYzllZjgyY2I5NDZm"