{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rbac.namespace }}
  labels:
    app: monitoring
    environment: {{ .Values.global.environment }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.namespace }}
  labels:
    app: monitoring
    environment: {{ .Values.global.environment }}
automountServiceAccountToken: false
{{- end }}
