apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: python
  labels:
    app: user-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      environment: dev
  template:
    metadata:
      labels:
        app: user-service
        environment: dev
    spec:
      containers:
        - name: user-service
          image: jeevanugale/user_service:test-385161287ff6d10a175545734e7ae937b0eb7a6b
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: app-configs
            - secretRef:
                name: app-secrets
          
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"