apiVersion: v1
kind: Service
metadata:
  name: db-server
  namespace: python
  labels:
    app: python-app
    environment: dev
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db-server
  namespace: python
  labels:
    app: python-app
    environment: dev
subsets:
  - addresses:
      - ip: 192.168.33.30
    ports:
      - port: 3306