apiVersion: v1
kind: Service
metadata:
  name: db-server
  namespace: python
  labels:
    app: python-app
    environment: dev
spec:
  type: ExternalName
  externalName: 0.0.0.0
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP