apiVersion: v1
kind: Namespace
metadata:
  name: python
  labels:
    app: python-app
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: monitoring
    environment: dev